uktrade/lite-exporter-frontend

- templates/404.html
- templates/500.html
- Added simple error pages to replace the built in Django ones (when Debug = False)
> fix: Error Pages

- ui_automation_tests/pages/exporter_hub_page.py
- ui_automation_tests/tests/test_draft_and_submit.py
- ui_automation_tests/tests/test_good_sites.py
- ui_automation_tests/tests/test_list_of_goods.py
> Lt 1308 e2e tests

- pipeline/Jenkinsfile
- ui_automation_tests/docker-entry.sh
- ui_automation_tests/selenium-automation-run/Dockerfile
- ui_automation_tests/selenium-base-image/Dockerfile
Update Jenkinsfile to work with new Infrastucture.
> Fix docker error

- README.md
- ui_automation_tests/docker-entry.sh
- ui_automation_tests/features/add_goods.feature
- ui_automation_tests/features/add_users_setup.feature
- ui_automation_tests/features/login_invalid.feature
- ui_automation_tests/features/login_valid.feature
- ui_automation_tests/features/organisation_setup.feature
- ui_automation_tests/features/search_for_goods.feature
- ui_automation_tests/features/sites.feature
- ui_automation_tests/features/submit_application.feature
- ui_automation_tests/features/users.feature
- ui_automation_tests/step_defs/test_users_steps.py
small changes to tags, to be able to run by tag on jenkins 
put the user tests into steps
change to jenkinsfile
> Tags to jenkins

- apply_for_a_licence/views/common.py
- templates/apply_for_a_licence/overview.html
> bug-fix-additional-documents

- apply_for_a_licence/views/documents.py
> LT-1524-bug-confirmation-missing-error

- goodstype/views.py
- templates/apply_for_a_licence/goodstype/countries.html
- ui_automation_tests/features/submit_open_application.feature
- ui_automation_tests/pages/goods_countries_page.py
- ui_automation_tests/step_defs/test_open_application.py
Works now with and without JS, JS on page has been removed.
Adding e2es now
> Bug: LT-1623-select-all

- Pipfile
- ui_automation_tests/docker-entry.sh
- ui_automation_tests/e2e.txt
- ui_automation_tests/selenium-automation-run/Dockerfile
* parallel tests using parameter from jenkins job
> test: Parallel e2e tests

- templates/applications/standard-application-edit.html
Changed 'Value Per Good' to Value of Good' as per: https://uktrade.atlassian.net/browse/LT-1763?atlOrigin=eyJpIjoiZmQ2MWM5YWU5MTAyNDcxMGEzYjA4MjZhYTM2NWYzY2YiLCJwIjoiaiJ9
> Change for bug LT-1763

- .circleci/config.yml
- ui_automation_tests/selenium-automation-run/Dockerfile
bumping up chromedriver a few versions
Only to 73 as that seems to be the latest that chromium goes to
> test: Update chromedriver

- applications/forms/location.py
- applications/forms/reference_name.py
- applications/forms/sites.py
- applications/forms/told_by_an_official.py
- templates/applications/goods_locations/goods_locations.html
Replaced 'goods' with 'products'
> Content review of goods locations

- .circleci/config.yml
- templates/check_html_strings.py
String checker for finding HTML strings that are missing from lite_content.
Internal: https://github.com/uktrade/lite-internal-frontend/pull/274
> tool: HTML String Check

- templates/applications/goods_types/countries.html
- templates/applications/goods_types/index.html
- templates/applications/open-application-edit.html
- templates/applications/parties/third_parties.html
- templates/applications/parties/ultimate_end_users.html
- templates/applications/standard-application-edit.html
- templates/end_users/end_user.html
- templates/end_users/end_users.html
- templates/end_users/tabs/case-notes.html
- templates/goods/modals/delete_document.html
- ui_automation_tests/step_defs/test_open_application.py
- ui_automation_tests/step_defs/test_standard_application.py
Combined several PRs from Anthony into one, for efficiency
> Exporter content updates

- docker-compose.yml
refactor: service to use port 8300 in local docker-compose
> refactor: service to use port 8300 in local docker-compose

- pipeline/Jenkinsfile
Add devpopcorn parameter to jenkins
> Add parameter to Jenkins

- pipeline/Jenkinsfile
* Makes our Slack notifications more useful! 
*  Posts directly to lite-development-team!
*  No more useless info!
*  Emoji!
*  GDS colours!
*  UAT only!
> refactor: Slack messages

- templates/applications/goods-types/index.html
- templates/applications/goods/index.html
* Adds numbers to the goods tables inside of applications to make it easier for applicants to reference their goods
> feat: LT-1961 - Goods table numbers

- templates/applications/open-application-edit.html
- templates/applications/standard-application-edit.html
Changed 'Completed' to 'Saved'
Changed 'In progress' to 'Add document'
> Content changes 27 01 20

- applications/forms/common.py
- applications/forms/told_by_an_official.py
- applications/helpers/check_your_answers.py
- applications/views/documents.py
- applications/views/goods.py
- core/forms.py
- end_users/forms.py
- end_users/views.py
- goods/helpers.py
- goods/views.py
- templates/applications/goods-locations/goods-locations.html
- templates/applications/goods/preexisting.html
- templates/applications/submit.html
- templates/applications/task-lists/hmrc-application.html
- templates/goods/good.html
Lots of small edits, including html files
> Content changes 12 02 20

- templates/hmrc/select-organisation.html
- templates/sites/index.html
- templates/users/profile.html
- users/views.py
> Content changes 13 02 20

- applications/forms/parties.py
- applications/forms/third_party.py
- applications/helpers/check_your_answers.py
- applications/services.py
- applications/urls.py
- applications/views/clearance.py
- applications/views/parties/base.py
- applications/views/parties/consignees.py
- applications/views/parties/end_users.py
- applications/views/parties/third_parties.py
- conf/constants.py
- templates/applications/application.html
- templates/applications/check-your-answer.html
- templates/applications/parties/third-parties.html
- templates/applications/task-list.html
- ui_automation_tests/conftest.py
- ui_automation_tests/features/edit_mod_application.feature
- ui_automation_tests/features/goods.feature
- ui_automation_tests/features/submit_mod_application.feature
- ui_automation_tests/pages/standard_application/task_list.py
- F380 application requires clearance level
- F380 parties require clearance level
> feat: LT-1594 - Application and party clearance levels

- conf/context_processors.py
- core/helpers.py
- templates/users/profile.html
- users/urls.py
- users/views.py
Fixes
`On exporter you can navigate to members and try to add a user when you dont have the correct permission`
> feat: LT-2201 - Members page bug

- ui_automation_tests/features/members.feature
- ui_automation_tests/step_defs/test_members.py
Not needed as it's covered in API tests
> test: Remove broken test

- applications/forms/end_use_details.py
- Added the missing reference title above each ref number field in the first two questions of the `End use details` section as per the designs
> fix: LT-1233 - add missing reference string

- templates/licences/licence.html
- ui_automation_tests/step_defs/test_licences.py
- Licence page now refers to the correct control list entries
> fix: LT-2359 - Multiple CLCs

- apply_for_a_licence/forms/triage_questions.py
- apply_for_a_licence/views.py
- ui_automation_tests/step_defs/test_standard_application.py
- Set `permanent` as default Transhipment `export_type`
> LT-2408: Transhipment export_type permanent

- ui_automation_tests/conftest.py
- ui_automation_tests/features/licences.feature
- ui_automation_tests/features/menu.feature
- ui_automation_tests/features/withdraw_and_surrender_application.feature
> fix: Flags in tests

- applications/helpers/task_lists.py
- applications/views/locations.py
- templates/applications/goods-locations/goods-locations.html
- templates/applications/task-list.html
- also fixes displaying the licence type when editing
> bug: LT-2243 - Hide change to sites/locations button on minor edits

- templates/check_html_strings.py
- templates/organisation/sites/site.html
It now handles multiple lcs usages on one line in HTML
> fix: Updated content string checker regex pattern

- ui_automation_tests/conftest.py
- ui_automation_tests/features/case_notes.feature
- ui_automation_tests/features/ecju_queries.feature
- ui_automation_tests/features/end_user_advisory_queries.feature
- ui_automation_tests/features/goods.feature
- ui_automation_tests/features/members.feature
- ui_automation_tests/features/menu.feature
- ui_automation_tests/features/register_an_organisation.feature
- ui_automation_tests/features/submit_mod_application.feature
- ui_automation_tests/features/submit_open_application.feature
- ui_automation_tests/features/submit_standard_application.feature
- ui_automation_tests/features/withdraw_and_surrender_application.feature
- ui_automation_tests/pages/application_page.py
- ui_automation_tests/pages/shared.py
- ui_automation_tests/step_defs/test_goods.py
- ui_automation_tests/step_defs/test_members.py
- ui_automation_tests/step_defs/test_withdraw_and_surrender_application.py
* set_timeout_to doesn't work on browser stack so i am removing this
* removed verify_build and final tag and just changed it to smoke for menu test and regression for the rest
* fixed goods test because it wasnt working properly.
> test: Speed up tests

- applications/views/locations.py
- core/services.py
- templates/applications/goods-locations/goods-locations.html
The bug arised around removing the last external location, and having no context as to why nothing was happening. The API was returning an error, and we usually don't program to stop last being removed.
To fix I have made the error message present to the user.
> Bug: LT-2676 - remove external locations bug

- applications/views/common.py
- core/views.py
- ui_automation_tests/features/register_an_organisation.feature
- ui_automation_tests/step_defs/test_zregister_an_organisation.py
Add sanity check for Organisation
- confirming an organisation where there is nothing in review
- get list of application without registering an organisation
> Add sanity checks for organisation

- core/helpers.py
- organisation/sites/forms.py
- organisation/sites/services.py
- organisation/sites/views.py
> fix: LT-2720 - Add existing postcode prompt message

- applications/forms/countries.py
- applications/helpers/check_your_answers.py
- core/builtins/custom_tags.py
- templates/applications/goods/goods-detail-summary.html
- ui_automation_tests/step_defs/test_open_application.py
LT-2775: ensure licence expiry dates are valid
LT-2732: show incorporated on the application summary/check your answers page
+ remove UK as a selectable country on OIELs
> bugs: LT-2775, LT-2732

- applications/forms/parties.py
- applications/services.py
- applications/views/parties/base.py
- United Kingdom shouldn't be an option to select for end users on standard transhipments
> bug: LT-2794 - Disallow UK end users on SITLs

- core/builtins/custom_tags.py
- templates/applications/parties/third-parties.html
* Fix appearance of links/table
* Hide descriptors column if it isn't used
* Code indentation  
* Latest LITE Forms
> chore: Third parties improvements

- applications/forms/end_use_details.py
- applications/forms/parties.py
- applications/forms/third_party.py
- applications/helpers/check_your_answers.py
- applications/views/parties/third_parties.py
- core/builtins/custom_tags.py
- templates/applications/parties/preexisting.html
- templates/applications/parties/third-parties.html
- templates/applications/parties/ultimate-end-users.html
- templates/applications/task-list.html
- ui_automation_tests/step_defs/test_standard_application.py
* LT-2253 - Selecting other on select the role of the third party question should force user to give a description
* Small content/form tidy up
> fix: LT-2253 - Selecting other on select the role of the third party question should force user to give a description
